name: Run Bitget Trading Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
      OKX_API_SECRET: ${{ secrets.OKX_API_SECRET }}
      OKX_API_PASSPHRASE: ${{ secrets.OKX_API_PASSPHRASE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.OKX_TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.OKX_TELEGRAM_CHAT_ID }}
      BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
      BITGET_API_SECRET: ${{ secrets.BITGET_API_SECRET }}
      BITGET_API_PASSPHRASE: ${{ secrets.BITGET_API_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/fut-bot"

      - name: Run bot container on remote server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/deleteWebhook";
            cd ~/fut-bot;
            docker stop fut-bot || true;
            docker rm fut-bot || true;
            docker system prune -a -f || true;
            docker build -t fut-bot .;
            docker run -d --name fut-bot -p 8000:8000 \
              -v ~/state:/app/state \
              -e OKX_API_KEY=${{ secrets.OKX_API_KEY }} \
              -e OKX_API_SECRET=${{ secrets.OKX_API_SECRET }} \
              -e OKX_API_PASSPHRASE=${{ secrets.OKX_API_PASSPHRASE }} \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.OKX_TELEGRAM_TOKEN }} \
              -e TELEGRAM_CHAT_ID=${{ secrets.OKX_TELEGRAM_CHAT_ID }} \
              -e BITGET_API_KEY=${{ secrets.BITGET_API_KEY }} \
              -e BITGET_API_SECRET=${{ secrets.BITGET_API_SECRET }} \
              -e BITGET_API_PASSPHRASE=${{ secrets.BITGET_API_PASSWORD }} \
              fut-bot &
